version: "3"
services:
  maven:
    build: .
    container_name: performance-test
    volumes:
      - /opt/results:/maven/target/results
      - /opt/.m2:/root/.m2
    command: ["mvn", "-B", "package"] 